name: hey_flutter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animator:
  flutter_statusbarcolor:
  shared_preferences:
  auto_size_text:
  font_awesome_flutter:
  circular_reveal_animation:
  cached_network_image:
  uni_links:
  dio:
  fluttertoast:
  basic_utils:
  loading:
  flutter_svg:

  image_picker:
  image_crop:
  page_indicator:
  animated_background:
  intl:
  flutter_datetime_picker:
  after_layout:

  flutter_launcher_icons:

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/icon_back.png"
  adaptive_icon_foreground: "assets/launcher/icon_top.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/launcher/

  fonts:
    - family: OpenSans
      fonts:
      - asset: fonts/OpenSans/OpenSans-Regular.ttf
      - asset: fonts/OpenSans/OpenSans-RegularItalic.ttf
        style: italic
      - asset: fonts/OpenSans/OpenSans-Bold.ttf
        weight: 700
      - asset: fonts/OpenSans/OpenSans-BoldItalic.ttf
        style: italic
        weight: 700

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
        - asset: fonts/Montserrat/Montserrat-RegularItalic.ttf
          style: italic
        - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat/Montserrat-BoldItalic.ttf
          style: italic
          weight: 700

    - family: LouisGeorgeCafe
      fonts:
        - asset: fonts/LouisGeorgeCafe/LouisGeorgeCafe.ttf
        - asset: fonts/LouisGeorgeCafe/LouisGeorgeCafe-Italic.ttf
          style: italic
        - asset: fonts/LouisGeorgeCafe/LouisGeorgeCafe-Bold.ttf
          weight: 700
        - asset: fonts/LouisGeorgeCafe/LouisGeorgeCafe-Bold-Italic.ttf
          style: italic
          weight: 700

    - family: LemonMilk
      fonts:
        - asset: fonts/LemonMilk/LemonMilk.otf
        - asset: fonts/LemonMilk/LemonMilkitalic.otf
          style: italic
        - asset: fonts/LemonMilk/LemonMilkbold.otf
          weight: 700
        - asset: fonts/LemonMilk/LemonMilkbolditalic.otf
          style: italic
          weight: 700